Minor syntax change in .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -38,35 +38,25 @@ python:
   - "3.6"
 
 before_install:
-  - |
-    pip install -U pip
-    pip install wheel coveralls>=1.1 --upgrade
-    pip install setuptools==36.0.1
-    pip install wheel
-  - |
-    . ./scripts/travis_gdal_install.sh
-    export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
-    export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
-    export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
-    export PROJ_LIB=/usr/share/proj
-    gdal-config --version
+  - pip install -U pip
+  - pip install wheel coveralls>=1.1 --upgrade
+  - pip install setuptools==36.0.1
+  - pip install wheel
+  - . ./scripts/travis_gdal_install.sh
+  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
+  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
+  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
+  - export PROJ_LIB=/usr/share/proj
+  - gdal-config --version
 
 install:
-  - |
-    pip install -r requirements-dev.txt
-    if [ "$GDALVERSION" = "trunk" ]; then
-      echo "Using gdal trunk"
-    elif [ $(gdal-config --version) == "$GDALVERSION" ]; then
-      echo "Using gdal $GDALVERSION"
-    else
-      echo "NOT using gdal $GDALVERSION as expected; aborting"
-      exit 1
-    fi
-    pip install --upgrade --force-reinstall --global-option=build_ext --global-option='-I$GDALINST/gdal-$GDALVERSION/include' --global-option='-L$GDALINST/gdal-$GDALVERSION/lib' --global-option='-R$GDALINST/gdal-$GDALVERSION/lib' -e .
-    pip install -e .[test]
-    fio --version
-    gdal-config --version
-    fio --gdal-version
+  - pip install -r requirements-dev.txt
+  - if [ "$GDALVERSION" = "trunk" ]; then echo "Using gdal trunk"; elif [ $(gdal-config --version) == "$GDALVERSION" ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
+  - pip install --upgrade --force-reinstall --global-option=build_ext --global-option='-I$GDALINST/gdal-$GDALVERSION/include' --global-option='-L$GDALINST/gdal-$GDALVERSION/lib' --global-option='-R$GDALINST/gdal-$GDALVERSION/lib' -e .
+  - pip install -e .[test]
+  - fio --version
+  - gdal-config --version
+  - fio --gdal-version
 
 script:
   - pytest --cov fiona --cov-report term-missing
@@ -75,7 +65,4 @@ after_success:
   - coveralls || echo "!! intermittent coveralls failure"
 
 before_cache:
-  - |
-    if [ "$GDALVERSION" = "trunk" ]; then
-      rm -rf $GDALINST/gdal-$GDALVERSION
-    fi
+  - if [ "$GDALVERSION" = "trunk" ]; then rm -rf $GDALINST/gdal-$GDALVERSION; fi
