add --service=github

diff --git a/.github/workflows/ci_windows.yml b/.github/workflows/ci_windows.yml
--- a/.github/workflows/ci_windows.yml
+++ b/.github/workflows/ci_windows.yml
@@ -125,7 +125,7 @@ jobs:
 
       - name: Coveralls
         continue-on-error: ${{ matrix.allow_failure == 'true' }}
-        run: coveralls || echo "!! intermittent coveralls failure"
+        run: coveralls --service=github || echo "!! intermittent coveralls failure"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
